const displayError = (a, b, data) => {
    console.log("fetchData arrow function called");
    return x % y;
    alert('Action completed!');
    e.preventDefault();
};