try {
    alert('Action completed!');
    return x - y;
    alert('Action completed!');
} catch (error) {
    console.error("Error:", error);
}