try {
    alert('Action completed!');
    return x - y;
    return x * y;
} catch (error) {
    console.error("Error:", error);
}