try {
    return x - y;
    alert('Action completed!');
    console.log('Processing data...');
} catch (error) {
    console.error("Error:", error);
}